// swift-tools-version: 5.6

import PackageDescription

let package = Package(
  name: "firebase-binaries",
  platforms: [
    .macOS(.v10_15),
    .iOS(.v13),
    .tvOS(.v10),
    .watchOS(.v3)
  ],
  products: [
    .library(
      name: "firebase-binaries",
      targets: [
          "abseil",
          "BoringSSL-GRPC",
          "FirebaseAnalytics",
          "FirebaseAppCheckInterop",
          "FirebaseAuth",
          "FirebaseAuthInterop",
          "FirebaseCore",
          "FirebaseCoreDiagnostics",
          "FirebaseCoreExtension",
          "FirebaseCoreInternal",
          "FirebaseCrashlytics",
          "FirebaseFirestore",
          "FirebaseFirestoreSwift",
          "FirebaseInstallations",
          "FirebaseMessaging",
          "FirebaseStorage",
          "FirebaseStorageInternal",
          "GoogleAppMeasurement",
          "GoogleAppMeasurementIdentitySupport",
          "GoogleDataTransport",
          "GoogleUtilities",
          "gRPC-C++",
          "gRPC-Core",
          "GTMSessionFetcher",
          "leveldb-library",
          "Libuv-gRPC",
          "nanopb",
          "PromisesObjC",
      ]
    ),
  ],
  targets: [
    .binaryTarget(name: "abseil", path: "firebase-binaries/abseil.xcframework"),
    .binaryTarget(name: "BoringSSL-GRPC", path: "firebase-binaries/BoringSSL-GRPC.xcframework"),
    .binaryTarget(name: "FirebaseAnalytics", path: "firebase-binaries/FirebaseAnalytics.xcframework"),
    .binaryTarget(name: "FirebaseAppCheckInterop", path: "firebase-binaries/FirebaseAppCheckInterop.xcframework"),
    .binaryTarget(name: "FirebaseAuth", path: "firebase-binaries/FirebaseAuth.xcframework"),
    .binaryTarget(name: "FirebaseAuthInterop", path: "firebase-binaries/FirebaseAuthInterop.xcframework"),
    .binaryTarget(name: "FirebaseCore", path: "firebase-binaries/FirebaseCore.xcframework"),
    .binaryTarget(name: "FirebaseCoreDiagnostics", path: "firebase-binaries/FirebaseCoreDiagnostics.xcframework"),
    .binaryTarget(name: "FirebaseCoreExtension", path: "firebase-binaries/FirebaseCoreExtension.xcframework"),
    .binaryTarget(name: "FirebaseCoreInternal", path: "firebase-binaries/FirebaseCoreInternal.xcframework"),
    .binaryTarget(name: "FirebaseCrashlytics", path: "firebase-binaries/FirebaseCrashlytics.xcframework"),
    .binaryTarget(name: "FirebaseFirestore", path: "firebase-binaries/FirebaseFirestore.xcframework"),
    .binaryTarget(name: "FirebaseFirestoreSwift", path: "firebase-binaries/FirebaseFirestoreSwift.xcframework"),
    .binaryTarget(name: "FirebaseInstallations", path: "firebase-binaries/FirebaseInstallations.xcframework"),
    .binaryTarget(name: "FirebaseMessaging", path: "firebase-binaries/FirebaseMessaging.xcframework"),
    .binaryTarget(name: "FirebaseStorage", path: "firebase-binaries/FirebaseStorage.xcframework"),
    .binaryTarget(name: "FirebaseStorageInternal", path: "firebase-binaries/FirebaseStorageInternal.xcframework"),
    .binaryTarget(name: "GoogleAppMeasurement", path: "firebase-binaries/GoogleAppMeasurement.xcframework"),
    .binaryTarget(name: "GoogleAppMeasurementIdentitySupport", path: "firebase-binaries/GoogleAppMeasurementIdentitySupport.xcframework"),
    .binaryTarget(name: "GoogleDataTransport", path: "firebase-binaries/GoogleDataTransport.xcframework"),
    .binaryTarget(name: "GoogleUtilities", path: "firebase-binaries/GoogleUtilities.xcframework"),
    .binaryTarget(name: "gRPC-C++", path: "firebase-binaries/gRPC-C++.xcframework"),
    .binaryTarget(name: "gRPC-Core", path: "firebase-binaries/gRPC-Core.xcframework"),
    .binaryTarget(name: "GTMSessionFetcher", path: "firebase-binaries/GTMSessionFetcher.xcframework"),
    .binaryTarget(name: "leveldb-library", path: "firebase-binaries/leveldb-library.xcframework"),
    .binaryTarget(name: "Libuv-gRPC", path: "firebase-binaries/Libuv-gRPC.xcframework"),
    .binaryTarget(name: "nanopb", path: "firebase-binaries/nanopb.xcframework"),
    .binaryTarget(name: "PromisesObjC", path: "firebase-binaries/PromisesObjC.xcframework"),
  ],
  cxxLanguageStandard: .cxx14
)
